let products = [
    {id: 1000, title: "Rompecocos", price: 50, cartprice: 20, stock: 0, img:"./img/rompecoco.png", category: "Varios", bestsell: true},
    {id: 1001, title: "Anteojos Led Neon", price: 50, cartprice: 20, stock: 15, img:"./img/anteojos-led-neon.png", category: "Anteojos", bestsell: true},
    {id: 1002, title: "Collar Hawaiano", price: 50, cartprice: 20, stock: 12, img:"./img/collar-hawaiano.png", category: "Collares", bestsell: true},
    {id: 1003, title: "Corbata Fluor", price: 50, cartprice: 20, stock: 18, img:"./img/corbata-fluor.png", category: "Corbatas", bestsell: true},
    {id: 1004, title: "Pulseras Quimicas", price: 50, cartprice: 20, stock: 11, img:"./img/pulseras-quimicas.png", category: "Pulseras", bestsell: true},
    {id: 1005, title: "Anteojos Rayban", price: 50, cartprice: 20, stock: 19, img:"./img/rayban.png", category: "Anteojos", bestsell: true},
    {id: 1006, title: "Vincha Diabla", price: 50, cartprice: 20, stock: 13, img:"./img/vincha-diabla.png", category: "Vinchas", bestsell: true},
    {id: 1007, title: "Anteojos Lenon", price: 50, cartprice: 20, stock: 13, img:"./img/anteojos-lenon.png", category: "Anteojos", bestsell: false},
    {id: 1008, title: "Vincha Resorte", price: 50, cartprice: 20, stock: 13, img:"./img/vincha-resorte.png", category: "Vinchas", bestsell: false},
    {id: 1009, title: "Vincha Rasta Led", price: 50, cartprice: 20, stock: 13, img:"./img/vincha-rasta-led.png", category: "Vinchas", bestsell: false},
    {id: 1010, title: "Anteojos Formas Led", price: 50, cartprice: 20, stock: 13, img:"./img/anteojos-forma-led.png", category: "Anteojos", bestsell: false},
    {id: 1011, title: "Anteojos Quimicos", price: 50, cartprice: 20, stock: 13, img:"./img/anteojos-quimicos.png", category: "Anteojos", bestsell: false},
    {id: 1012, title: "Corbatas Led", price: 50, cartprice: 20, stock: 13, img:"./img/corbatas-led.png", category: "Corbatas", bestsell: false},
    {id: 1013, title: "Vincha Minnie", price: 50, cartprice: 20, stock: 13, img:"./img/vincha-minnie.png", category: "Vinchas", bestsell: false},
    {id: 1014, title: "Tiradores Fluor", price: 50, cartprice: 20, stock: 13, img:"./img/tiradores.png", category: "Varios", bestsell: false},
    {id: 1015, title: "Collar Hawaiano Led", price: 50, cartprice: 20, stock: 13, img:"./img/collar-hawaiano-led.png", category: "Collares", bestsell: false},
    {id: 1016, title: "Pulsera Acrilica Led", price: 50, cartprice: 20, stock: 13, img:"./img/pulsera-acrilica-led.png", category: "Pulseras", bestsell: false},
];